### ISSUE TITLE
Bug: `findRoot` fails to return root at midpoint of interval

### ISSUE THREAD

**Issue by HeinrichApfelmus** [DeltaQ-SD/deltaq#69]
The function `findRoot` is unable to find a root in the special case where the root is precisely at the midpoint of the interval.

Specifically, `findRoot` is unable find the root $x_2 := (a+b)/2$ of the cubic polynomial $p(x) = (x - a)(x - (a+b)/2)(x - b)$ on the interval $[a + ε, b-ε]$.

Instead of picking the starting point, the iterative procedure of `findRoot` veers off to one of the interval ends.

**Comment by peterwthompson** [comment]
Dealing with repeated roots consistently probably requires finding a square-free factorisation, for which we can use Yun's algorithm.

**Comment by HeinrichApfelmus** [comment]
I have split off #104 from this discussion. Sorry for the scope creep in the first place.
